apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: opaque
stringData:
  mongo-user: admin # required field for kubernetes.io/basic-auth
  mongo-password: passsword # required field for kubernetes.io/basic-auth